server:
  port: 5320

mwcs:
  security:
    ignored:
      - /file/**
    captcha:
      enabled: false
    sms:
      expireSeconds: 120

graceful-response:
  responseClassFullName: com.reebake.example.CustomResponseImpl
  printExceptionInGlobalAdvice: true

# Spring Boot Application Configuration
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mwcs_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
    driver-class: org.sqlite.JDBC
    url: jdbc:sqlite:../database/sqlite/ideal

# MyBatis-Plus Configuration
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sms:
  restricted: true
  account-max: 50
  minute-max: 2
  config-type: yaml
  blends:
    verify_code:
      supplier: alibaba
      access-key-id: 你的访问id
      access-key-secret: 你的访问密钥
      signature: 你的签名
#      template-id: 你的模板号

dromara:
  x-file-storage:
    default-platform: local-plus-1
    local-plus:
      - platform: local-plus-1 # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: http://192.168.1.13:5320/file/ # 访问域名，例如：“http://127.0.0.1:8030/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: local-plus/ # 基础路径
        path-patterns: /file/** # 访问路径
        storage-path: /Users/huangchengqing/reebake/upload/ # 存储路径
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: 你的访问key
        secret-key: 你的密钥key
        end-point: oss-cn-beijing.aliyuncs.com
        bucket-name: 你的bucket
        domain: https://test-hymy-com.oss-cn-beijing.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: test/ # 基础路径