server:
  port: 5320

mwcs:
  security:
    ignored:
    captcha:
      enabled: false
    sms:
      expireSeconds: 120
graceful-response:
  responseClassFullName: com.reebake.example.CustomResponseImpl